version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  request-handler:
    image: request-handler 
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - ENDPOINT=
      - UPLOAD_SERVICE_URL=http://upload-service:3000
    ports:
      - "3001:3001"
    restart: always

  upload-service:
    image: upload-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - ENDPOINT=
      - PORT=3000

    ports:
      - "3002:3002"
    restart: always

  deploy-service:
    image: deploy-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - ENDPOINT=
    restart: always
  
  vercel-frontend:
    image: vercel-frontend
    depends_on:
      - request-handler
      - deploy-service
      - upload-service
    environment:
      - VITE_APP_UPLOAD_SERVICE_URL=
    ports:
      - "5173:80"
    restart: always 

volumes:
  redis-data: